name: build-ipk (OpenWrt 24.10.3 x86_64)

on:
  push:
    tags: ['*']

permissions:
  contents: write

env:
  RELEASE: 24.10.3
  TARGET: x86
  SUBTARGET: 64
  PKG_DIR_NAME: luci-app-adguardhome

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 从 tag 写入 PKG_RELEASE
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "使用 Tag 作为 PKG_RELEASE: ${TAG}"
          sed -i "s/^PKG_RELEASE:=.*/PKG_RELEASE:=${TAG}/" Makefile
          grep -n '^PKG_RELEASE:=' Makefile || true

      - name: 安装构建依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget zstd

      - name: 下载并解压 SDK
        run: |
          set -eux
          BASE="https://downloads.openwrt.org/releases/${RELEASE}/targets/${TARGET}/${SUBTARGET}/"
          SDK_TARBALL=$(curl -fsSL "$BASE" | grep -o 'openwrt-sdk-[^"]*\.tar\.zst' | head -n1)
          mkdir -p _sdk
          wget -q "${BASE}${SDK_TARBALL}" -O _sdk/sdk.tar.zst
          tar --zstd -xf _sdk/sdk.tar.zst -C _sdk
          SDK_DIR="$(find "$PWD/_sdk" -maxdepth 1 -type d -name 'openwrt-sdk-*' -print -quit)"
          echo "SDK_DIR=${SDK_DIR}" >> "$GITHUB_ENV"
          echo "Resolved SDK_DIR=${SDK_DIR}"

      - name: 将包拷入 SDK
        run: |
          cd "$SDK_DIR"
          mkdir -p package/${PKG_DIR_NAME}
          rsync -a --delete "$GITHUB_WORKSPACE/" "package/${PKG_DIR_NAME}/" \
            --exclude '.git' --exclude '.github' --exclude '_sdk' --exclude 'out'

      - name: 仅更新 luci 源并安装 luci-base
        run: |
          cd "$SDK_DIR"
          ./scripts/feeds update luci
          ./scripts/feeds install luci-base

      - name: 生成默认配置
        run: |
          cd "$SDK_DIR"
          make defconfig

      - name: 编译包
        run: |
          cd "$SDK_DIR"
          make package/${PKG_DIR_NAME}/clean V=s || true
          make package/${PKG_DIR_NAME}/compile -j"$(nproc)" V=sc

      - name: 收集构建产物
        run: |
          cd "$SDK_DIR"
          mkdir -p "$GITHUB_WORKSPACE/out"
          find bin/packages -type f -name "*${PKG_DIR_NAME}*ipk" -print -exec cp -f {} "$GITHUB_WORKSPACE/out/" \;
          cd "$GITHUB_WORKSPACE/out" && sha256sum *.ipk > SHA256SUMS.txt || true && ls -l

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ipks-${{ github.ref_name }}-x86_64
          path: out/
          if-no-files-found: error

      - name: 发布到 Releases
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            out/*.ipk
